# Generated by Django 5.1.4 on 2025-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
